### PR TITLE
feat: Add precommit config

### PR DESCRIPTION
**Pull request by ximena9201**
This adds pre-commit. It will run `terraform fmt `in a Github action for pull requests and pushes on master. It will avoid bad syntax and will keep the files formatted.

Reference:
https://github.com/antonbabenko/pre-commit-terraform#terraform_fmt

### CODE REVIEW

**Comment by ximena9201** [comment]
The files have been formatted, and nothing in the logic has changed.

**Comment by ZavenArra** [comment]
great.  looks good to me!

**Comment by ZavenArra** [comment]
@ximena9201 can we investigate why the CI job is failing on this one before I merge?

**Review by ZavenArra — APPROVED** [review]
Looks great!

**Pull request merged**
